# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build_github_pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build for GitHub Pages
        run: npm run build-github-pages
      - name: Upload GitHub Pages artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-github-pages-artifact
          path: "./out"

  build_codeberg_pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build for Codeberg Pages
        run: npm run build-codeberg-pages
      - name: Upload Codeberg Pages artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-codeberg-pages-artifact
          path: "./out"

  deploy_to_github_pages:
    needs: build_github_pages
    runs-on: ubuntu-latest
    steps:
      - name: Download GitHub Pages artifact
        uses: actions/download-artifact@v3
        with:
          name: build-github-pages-artifact
          path: "./out"
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact to GitHub Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: "./out"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

  deploy_to_codeberg_pages:
    needs: build_codeberg_pages
    runs-on: ubuntu-latest
    steps:
      - name: Download Codeberg Pages artifact
        uses: actions/download-artifact@v3
        with:
          name: build-codeberg-pages-artifact
          path: "./out"
      - name: Setup Git Config
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      - name: Push to Codeberg
        run: |
          cd ./out
          git init
          git add .
          git commit -m "Deploy to Codeberg"
          git branch -M pages
          git remote add origin https://mshibanami:${{ secrets.CODEBERG_TOKEN }}@codeberg.org/mshibanami/jisk.git
          git push -f origin pages
